### ISSUE TITLE
Support for Vue.js

### ISSUE THREAD

**Issue by nivv** [othree/javascript-libraries-syntax.vim#50]
Would be nice to add suport for Vue.js

**Comment by othree** [comment]
Could you help me summarize some data, [sample here](https://github.com/othree/javascript-libraries-syntax.vim/issues/34#issuecomment-216404353)

**Comment by nivv** [comment]
Sure. 

Vue components are mashed up in a template, script tag and css. Simple example below:

```html
<style>
.js-spinner {
    position: absolute;
}
</style>

<template>
    <div style="position:relative">
        <div class="js-spinner" id="loadSpinner" v-el:spinner></div>
    </div>
</template>

<script>
export default {
    name: 'SpinLoader',
    props: {
        loading: {
            type: Boolean,
            default: true
        },
        position: {
            type: String,
            default: 'absolute'
        }
    },
    ready: function() {
        this.startSpinner();
    },
    watch: {
        loading: function(value) {
            if (value === false) {
                this.stopSpinner();
            } else {
                this.startSpinner();
            }
        }
    },
    methods: {
        startSpinner: function() {
            var Spinner = require('spin.js');
            var opts = {
                width: this.width,
                scale: this.scale,
                lines: this.lines,
                color: this.color,
                shadow: this.shadow,
                //radius: this.radius,
                position: this.position
            }

            var target = this.$els.spinner;
            this.spinner = new Spinner(opts).spin(target);
        },
        stopSpinner: function() {
            this.spinner.stop();
        }
    },
    data() {
        return {
            spinner: {},
        }
    }
}

</script>
```

The JS in the script tags are pretty much spot on already. I'll list the custom elements that can be attached in the templates below:

### Class binding

`<div class="static" v-bind:class="{ 'class-a': isA, 'class-b': isB }"></div>`
Short hand of above (true for all `v-bind`)
`<div class="static" @class="{ 'class-a': isA, 'class-b': isB }"></div>`

**Comment by Blackskyliner** [comment]
If you just want support for the .vue specific case (its just that it has more than 1 file context, e.g. template, style, script) you can use https://github.com/posva/vim-vue which will split those apart and let vim handle the blocks in their respective language. (as far is I understood - no vim pro here)

The completion for the html-custom-attribs and all omni completion stuff however would be needed to get implemented via another plugin, like the current one this issue is opened in.

So a list of all custom html attributes in their variations would be needed. Also the methods/interfaces the Vue class offers. (e.g. methods, utils, ...).

**Comment by othree** [comment]
I think @Blackskyliner's suggestion is very good.
I will add custom attributes to html for vue first.
And you should be able to see it by vim-vue.
