### ISSUE TITLE
Looks like plugin not works for me

### ISSUE THREAD

**Issue by azat-io** [othree/javascript-libraries-syntax.vim#61]
Here is a part of my Vim config file:
```vim
" Scripts

Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'othree/javascript-libraries-syntax.vim', { 'for': 'javascript' }
Plug 'fleischie/vim-styled-components', { 'for': 'javascript' }

let g:javascript_plugin_jsdoc = 1
let g:used_javascript_libs = 'react,vue,underscore,jasmine'
```
Your plugin works good for me some time ago. But now it looks like not.

All plugins was updated today. What's wrong here?

![screenshot from 2017-03-28 16-08-09](https://cloud.githubusercontent.com/assets/5698350/24406495/14e3851e-13d1-11e7-89bd-710b04931b7c.png)

**Comment by othree** [comment]
Can you disable all other syntax highlight script for JavaScript to test?
At least the word `React` should be highlighted.

<img width="262" alt="2017-03-28 9 26 36" src="https://cloud.githubusercontent.com/assets/16474/24407410/60fbae00-13fd-11e7-8c22-7faafee6c034.png">

**Comment by azat-io** [comment]
@othree `React` word is highlighted, but nothing else

![screenshot from 2017-03-28 16-29-54](https://cloud.githubusercontent.com/assets/5698350/24407631/27750f38-13d4-11e7-94f4-8e49e37f3cf1.png)

**Comment by azat-io** [comment]
Looks like here this plugin highlight only `React` word

**Comment by othree** [comment]
I think you are looking for highlight of the word `Component`.
But it will not highlight for current implementation.
`React.Component` will be highlighted. But `Component` only will not.

This approach works well in old times(before ES import).
I am looking for a balance point for this.
Because some library have very common keywords.

Keywords from React are not so common or short.
So maybe I will just let they all be global keywords.
But still not sure.

**Comment by azat-io** [comment]
Looks like the problem was fixed with https://github.com/othree/javascript-libraries-syntax.vim/commit/3d0039fe05ae684787d03266a0715758eb5ac495
